#!/usr/bin/env python3
"""Prepare and evaluate deterministic synthetic Body Calculator transforms.

The transformed image cache is deliberately external to git.  The committed
manifest binds every generated byte so the production browser batch can be
reproduced without committing the source or derivative stimulus images.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import sys
import json
import math
import shutil
from collections import Counter, defaultdict
from pathlib import Path

import PIL
import numpy as np
import onnxruntime as ort
from PIL import Image, ImageEnhance, ImageFilter, ImageOps

from compare_body_preprocessing import load_reference, preprocess, score_from_raw
from evaluate_body_accuracy import crop_padding_diagnostic, display_number, file_sha256, number, numeric_distribution, pairwise_accuracy, pearson, public_half_point, spearman


TRANSFORMS = (
    ("original", "control", "Unmodified source bytes."),
    ("mirror", "mirror", "Horizontal mirror."),
    ("crop_center_10", "crop", "Crop 10% from every edge."),
    ("crop_legs_20", "crop", "Crop the bottom 20% of the frame."),
    ("pad_wide_black", "padding_aspect", "Black side padding to 1.4x width."),
    ("pad_tall_black", "padding_aspect", "Black top/bottom padding to 1.3x height."),
    ("canvas_light_gray", "background_canvas", "Light-gray canvas with 12.5% padding per edge."),
    ("aspect_squeeze_80", "padding_aspect", "Resample width to 80% without preserving aspect."),
    ("resolution_256", "resolution", "Downsample longest edge to 256 pixels."),
    ("brightness_70", "lighting", "Global brightness multiplier 0.70."),
    ("brightness_130", "lighting", "Global brightness multiplier 1.30."),
    ("contrast_70", "lighting", "Global contrast multiplier 0.70."),
    ("contrast_130", "lighting", "Global contrast multiplier 1.30."),
    ("side_lighting", "lighting", "Deterministic left-to-right 0.60x to 1.30x luminance gradient."),
    ("jpeg_q35", "jpeg", "JPEG re-encode at quality 35."),
    ("rotate_3", "rotation_camera_like", "Rotate +3 degrees in-place with black fill."),
    ("perspective_mild", "rotation_camera_like", "Mild deterministic perspective-like quadrilateral warp."),
    ("gaussian_blur_1_5", "rotation_camera_like", "Gaussian blur radius 1.5 as a camera-focus proxy."),
)


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv(path: Path):
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows, columns):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def sha_bytes(data: bytes):
    return hashlib.sha256(data).hexdigest()


def pick_evenly(rows, count):
    rows = sorted(rows, key=lambda row: (float(row["attractiveness_mean"]), row["image_id"]))
    if count >= len(rows):
        return rows
    if count == 1:
        return [rows[len(rows) // 2]]
    indices = [round(index * (len(rows) - 1) / (count - 1)) for index in range(count)]
    return [rows[index] for index in indices]


def select_stratified(manifest_rows, batch_rows):
    outcomes = {row["image_id"]: row.get("outcome", "") for row in batch_rows}
    ordered = sorted(manifest_rows, key=lambda row: (float(row["attractiveness_mean"]), row["image_id"]))
    selected = []
    for quartile in range(4):
        start = math.floor(quartile * len(ordered) / 4)
        end = math.floor((quartile + 1) * len(ordered) / 4)
        group = ordered[start:end]
        scored = [row for row in group if outcomes.get(row["image_id"]) == "scored"]
        refused = [row for row in group if outcomes.get(row["image_id"]) != "scored"]
        picks = []
        if scored and refused:
            picks.extend(pick_evenly(scored, 1))
            picks.extend(pick_evenly(refused, 1))
        remaining = [row for row in group if row not in picks]
        picks.extend(pick_evenly(remaining, 3 - len(picks)))
        for row in picks:
            selected.append({**row, "label_quartile": str(quartile + 1), "baseline_outcome": outcomes.get(row["image_id"], "")})
    if len(selected) != 12 or len({row["image_id"] for row in selected}) != 12:
        raise ValueError("stratified selection must produce 12 unique source stimuli")
    return selected


def rgb_image(path: Path):
    with Image.open(path) as source:
        return ImageOps.exif_transpose(source).convert("RGB")


def transformed(image: Image.Image, name: str):
    width, height = image.size
    if name == "mirror":
        return ImageOps.mirror(image)
    if name == "crop_center_10":
        return image.crop((round(width * .10), round(height * .10), round(width * .90), round(height * .90)))
    if name == "crop_legs_20":
        return image.crop((0, 0, width, round(height * .80)))
    if name == "pad_wide_black":
        canvas = Image.new("RGB", (round(width * 1.4), height), "black")
        canvas.paste(image, ((canvas.width - width) // 2, 0))
        return canvas
    if name == "pad_tall_black":
        canvas = Image.new("RGB", (width, round(height * 1.3)), "black")
        canvas.paste(image, (0, (canvas.height - height) // 2))
        return canvas
    if name == "canvas_light_gray":
        canvas = Image.new("RGB", (round(width * 1.25), round(height * 1.25)), (224, 224, 224))
        canvas.paste(image, ((canvas.width - width) // 2, (canvas.height - height) // 2))
        return canvas
    if name == "aspect_squeeze_80":
        return image.resize((round(width * .8), height), Image.Resampling.BILINEAR)
    if name == "resolution_256":
        output = image.copy()
        output.thumbnail((256, 256), Image.Resampling.LANCZOS)
        return output
    if name == "brightness_70":
        return ImageEnhance.Brightness(image).enhance(.70)
    if name == "brightness_130":
        return ImageEnhance.Brightness(image).enhance(1.30)
    if name == "contrast_70":
        return ImageEnhance.Contrast(image).enhance(.70)
    if name == "contrast_130":
        return ImageEnhance.Contrast(image).enhance(1.30)
    if name == "side_lighting":
        pixels = np.asarray(image, dtype=np.float32)
        gradient = np.linspace(.60, 1.30, width, dtype=np.float32)[None, :, None]
        return Image.fromarray(np.clip(pixels * gradient, 0, 255).astype(np.uint8), "RGB")
    if name == "jpeg_q35":
        return image.copy()
    if name == "rotate_3":
        return image.rotate(3, resample=Image.Resampling.BILINEAR, expand=False, fillcolor="black")
    if name == "perspective_mild":
        inset_x, inset_y = width * .035, height * .025
        quad = (inset_x, inset_y, 0, height - inset_y, width - inset_x, height, width, 0)
        return image.transform(image.size, Image.Transform.QUAD, quad, Image.Resampling.BILINEAR, fillcolor="black")
    if name == "gaussian_blur_1_5":
        return image.filter(ImageFilter.GaussianBlur(1.5))
    raise ValueError(f"unknown transform {name}")


def save_transform(source_path: Path, output_path: Path, name: str):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if name == "original":
        shutil.copyfile(source_path, output_path)
    else:
        image = transformed(rgb_image(source_path), name)
        quality = 35 if name == "jpeg_q35" else 95
        image.save(output_path, format="JPEG", quality=quality, subsampling=0, optimize=False)
    with Image.open(output_path) as check:
        dimensions = check.size
    return dimensions, file_sha256(output_path)


def prepare(args):
    source_manifest = Path(args.source_manifest).resolve()
    source_batch = Path(args.source_batch).resolve()
    source_metadata = Path(args.source_metadata).resolve()
    photos = Path(args.photos).resolve()
    cache = Path(args.cache_dir).resolve()
    manifest_out = Path(args.manifest_out)
    metadata_out = Path(args.metadata_out)
    manifest_rows = read_csv(source_manifest)
    batch_rows = read_csv(source_batch)
    metadata = read_json(source_metadata)
    batch_metadata = read_json(Path(args.source_batch_metadata).resolve())
    if metadata.get("manifest_sha256") != file_sha256(source_manifest):
        raise ValueError("source dataset metadata does not bind to source manifest")
    if batch_metadata.get("output_csv_sha256") != file_sha256(source_batch):
        raise ValueError("source batch metadata does not bind to source batch")
    if batch_metadata.get("manifest_sha256") != file_sha256(source_manifest):
        raise ValueError("source batch metadata does not bind to source manifest")
    chosen = select_stratified(manifest_rows, batch_rows)
    output_rows = []
    descriptions = {name: {"family": family, "description": description} for name, family, description in TRANSFORMS}
    for source in chosen:
        source_path = photos / source["filename"]
        if file_sha256(source_path) != source["image_sha256"]:
            raise ValueError(f"source hash mismatch: {source['filename']}")
        for name, family, _ in TRANSFORMS:
            filename = f"{source['image_id']}__{name}.jpg"
            dimensions, digest = save_transform(source_path, cache / filename, name)
            output_rows.append({
                "image_id": f"{source['image_id']}__{name}",
                "filename": filename,
                "image_sha256": digest,
                "source_image_id": source["image_id"],
                "source_filename": source["filename"],
                "transform": name,
                "transform_family": family,
                "label_quartile": source["label_quartile"],
                "baseline_outcome": source["baseline_outcome"],
                "attractiveness_mean": source["attractiveness_mean"],
                "identity_group": source.get("identity_group") or source["image_id"],
                "width": dimensions[0],
                "height": dimensions[1],
            })
    columns = list(output_rows[0])
    write_csv(manifest_out, output_rows, columns)
    manifest_hash = file_sha256(manifest_out)
    report = {
        "schema_version": "body-transform-stability-dataset.v1",
        "dataset": "Deterministic synthetic transforms of the Moussally body-only independent stimuli",
        "cases": len(output_rows),
        "manifest_sha256": manifest_hash,
        "source_dataset_metadata_sha256": file_sha256(source_metadata),
        "source_manifest_sha256": file_sha256(source_manifest),
        "source_batch_sha256": file_sha256(source_batch),
        "source_batch_metadata_sha256": file_sha256(Path(args.source_batch_metadata).resolve()),
        "selection": {
            "method": "Three deterministic label-ordered samples per quartile; a scored/refused mix is forced where both exist.",
            "source_cases": len(manifest_rows),
            "selected_cases": len(chosen),
            "selected_ids": [row["image_id"] for row in chosen],
            "selected_by_quartile": dict(Counter(row["label_quartile"] for row in chosen)),
            "selected_by_frozen_outcome": dict(Counter(row["baseline_outcome"] for row in chosen)),
        },
        "transforms": descriptions,
        "label": {
            **metadata["label"],
            "field": "attractiveness_mean",
            "cluster_field": "source_image_id",
        },
        "provenance": {
            "source": metadata.get("provenance"),
            "copyright_and_cache": "Source and derivative image files remain in an external cache and are not committed. The manifest commits hashes only.",
        },
        "generation": {
            "tool_sha256": file_sha256(Path(__file__).resolve()),
            "python": sys.version.split()[0],
            "pillow": PIL.__version__,
            "numpy": np.__version__,
            "command": [sys.executable, str(Path(__file__).resolve()), *sys.argv[1:]],
            "external_cache_root": str(cache),
        },
        "scope": {
            "intended_use": "Engineering stability diagnostic, not a new subjective-accuracy test and not candidate tuning.",
            "limitations": [
                "All sources are synthetic female bodies on one shape continuum.",
                "Pixel transforms do not create independent human judgments.",
                "Synthetic transforms do not prove physical sensor rotation, autofocus, exposure, browser permission behavior, real motion, new poses, or arm placement.",
                "No clothed, bare-torso, male, or demographic breadth is supplied by this set.",
            ],
        },
    }
    metadata_out.parent.mkdir(parents=True, exist_ok=True)
    metadata_out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"cases": len(output_rows), "sources": len(chosen), "manifest_sha256": manifest_hash}, indent=2))


def current_continuous(row):
    explicit = display_number(row.get("bp_continuous"))
    if explicit is not None:
        return explicit
    return display_number(row.get("bp"))


def current_public(row):
    explicit = display_number(row.get("public_score"))
    if explicit is not None:
        return explicit
    continuous = current_continuous(row)
    return public_half_point(continuous) if continuous is not None else None


def score_form(row):
    value = str(row.get("bp_continuous") or row.get("bp") or "")
    if display_number(value) is None:
        return "none"
    return "interval_midpoint" if "–" in value else "scalar"


def interval_width(row):
    value = str(row.get("bp_continuous") or row.get("bp") or "")
    if "–" not in value:
        return 0.0 if display_number(value) is not None else None
    low, high = (number(part) for part in value.split("–", 1))
    return high - low if low is not None and high is not None else None


def ordering(original, transformed_rows, score_key):
    pairs = []
    for source_id, baseline in original.items():
        row = transformed_rows.get(source_id)
        if not row:
            continue
        left, right = baseline.get(score_key), row.get(score_key)
        if left is not None and right is not None:
            pairs.append((source_id, left, right))
    if len(pairs) < 2:
        return {"paired_sources": len(pairs), "spearman_vs_original": None, "pairwise_order_agreement": None, "pairwise_pairs": 0}
    base = [pair[1] for pair in pairs]
    changed = [pair[2] for pair in pairs]
    agreement = pairwise_accuracy(changed, base, (0,))["0"]
    return {
        "paired_sources": len(pairs),
        "spearman_vs_original": spearman(base, changed),
        "pairwise_order_agreement": agreement["accuracy"],
        "pairwise_pairs": agreement["pairs"],
    }


def summarize_delta(values):
    finite = [value for value in values if value is not None and math.isfinite(value)]
    return {
        "n": len(finite),
        "mean_signed": sum(finite) / len(finite) if finite else None,
        "mean_absolute": sum(abs(value) for value in finite) / len(finite) if finite else None,
        "maximum_absolute": max((abs(value) for value in finite), default=None),
        "rmse": math.sqrt(sum(value * value for value in finite) / len(finite)) if finite else None,
    }


def grouped(rows, field):
    groups = defaultdict(list)
    for row in rows:
        groups[str(row.get(field) or "unknown")].append(row)
    result = {}
    for value, group in sorted(groups.items()):
        current_pairs = [row["current_delta"] for row in group if row.get("current_delta") is not None]
        candidate_pairs = [row["candidate_delta"] for row in group if row.get("candidate_delta") is not None]
        result[value] = {
            "rows": len(group),
            "current_scored": sum(row.get("current_continuous") is not None for row in group),
            "current_refusal_rate": sum(row.get("current_continuous") is None for row in group) / len(group),
            "current_route_transitions": sum(bool(row.get("route_transition")) for row in group),
            "current_delta": summarize_delta(current_pairs),
            "candidate_delta": summarize_delta(candidate_pairs),
        }
    return result


def markdown(report):
    overview = report["overview"]
    screen = report["candidate_stability_screen"]
    lines = [
        "# Body preprocessing transform-stability audit",
        "",
        "## Result",
        "",
        f"The audit ran {overview['rows']} production browser cases: {overview['sources']} source stimuli × {overview['transforms']} deterministic states. "
        f"The production route scored {overview['current_scored']} rows and refused {overview['current_refused']} ({overview['current_refusal_rate']:.1%}).",
        "",
        f"Across non-control cases with a scored original and transformed production result, the current pipeline's mean absolute continuous-score change was {overview['current_delta']['mean_absolute']:.4f}. "
        f"On those identical production-accepted pairs, the locked full-letterbox candidate's mean absolute change was {overview['candidate_delta_common_current_pairs']['mean_absolute']:.4f}. "
        "These are stability measurements, not independently judged attractiveness improvements.",
        f"The descriptive common-pair screen flagged {len(screen['material_regressions'])} transformed states where candidate MAE worsened by more than 0.10 or rank retention worsened by more than 0.10. These reporting thresholds were not preregistered acceptance cutoffs.",
        "",
        "",
        "## Per-transform results",
        "",
        "| Transform | Current scored | Refused | Route changes | Current MAE | Current rank retention | Candidate MAE | Candidate rank retention |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for name, item in report["by_transform"].items():
        def fmt(value):
            return "—" if value is None else f"{value:.4f}"
        lines.append(
            f"| {name} | {item['current_scored']}/{item['sources']} | {item['current_refused']} | {item['route_transitions']} | "
            f"{fmt(item['current_delta']['mean_absolute'])} | {fmt(item['current_ordering']['spearman_vs_original'])} | "
            f"{fmt(item['candidate_delta_common_current_pairs']['mean_absolute'])} | {fmt(item['candidate_ordering_common_current_pairs']['spearman_vs_original'])} |"
        )
    crop = report["crop_padding_diagnostic"]
    padding = crop["padding_fraction"]
    outcome = crop["outcome_sensitivity"]
    scores = crop["score_sensitivity"]
    paired = crop["paired_score_delta_sensitivity"]
    change = crop["paired_padding_change_sensitivity"]
    lines.extend([
        "",
        "## Production pose-crop padding",
        "",
        f"Crop geometry was instrumented for {crop['instrumented_rows']}/{crop['rows']} rows; "
        f"{crop['crop_outside_rows']} extended outside the image "
        f"({fmt(crop['crop_outside_rate_instrumented'])} of instrumented rows).",
        f"Padding fractions: min {fmt(padding['min'])}, q25 {fmt(padding['q25'])}, "
        f"median {fmt(padding['median'])}, q75 {fmt(padding['q75'])}, "
        f"p90 {fmt(padding['p90'])}, max {fmt(padding['max'])}.",
        f"Refusal/error rates were {fmt(outcome['crop_outside']['refusal_rate'])} for outside crops "
        f"(n={outcome['crop_outside']['n']}) and {fmt(outcome['crop_inside']['refusal_rate'])} "
        f"for inside crops (n={outcome['crop_inside']['n']}).",
        f"Among finite results, padding-versus-score Spearman was "
        f"{fmt(scores['padding_vs_continuous_score_spearman'])}; outside-minus-inside mean score was "
        f"{fmt(scores['outside_minus_inside_mean'])}. Paired transform MAE was "
        f"{fmt(paired['crop_outside']['mean_absolute'])} for outside crops versus "
        f"{fmt(paired['crop_inside']['mean_absolute'])} for inside crops.",
        f"Within-source padding-fraction change versus continuous-score change used {change['n']} pairs: "
        f"Spearman {fmt(change['padding_delta_vs_score_delta_spearman'])}, Pearson {fmt(change['padding_delta_vs_score_delta_pearson'])}.",
        change["interpretation"], crop["interpretation"],
        crop["comparison_limitation"],
    ])
    lines.extend([
        "",
        "## Route and refusal behavior",
        "",
        f"Observed route transitions: `{json.dumps(report['route_transitions'], sort_keys=True)}`.",
        "",
        f"Observed refusal reasons: `{json.dumps(report['refusal_reasons'], sort_keys=True)}`.",
        "",
        "Machine-readable slices by production route, inferred sex, framing state, surviving geometry cues, transform family, label quartile, and frozen baseline outcome are in the JSON artifact. Sparse slices are descriptive only.",
        "",
        "## Interpretation and limits",
        "",
        "The full-letterbox candidate is a preprocessing change and can alter ordering; it is not a monotone display remap. Public half-point quantization is reported separately because it adds ties and can obscure continuous differences. No calibration curve receives credit for ranking or ordering.",
        "",
        "This registered stability check is narrow: the sources are synthetic female bodies on one controlled shape continuum. Synthetic mirrors, crops, padding, resampling, lighting edits, background canvases, JPEG compression, rotation, perspective warps, and blur do **not** prove behavior for actual pose changes, arm placement, physical sensor rotation, autofocus, exposure, permission/browser chrome, or real-device motion. It also supplies no male, clothed, bare-torso, demographic, or real-background breadth.",
        "",
        report["interpretation"]["candidate_decision"],
        "",
        "## Reproduction",
        "",
        "Exact commands, input paths, hashes, model/page bindings, and the external-cache warning are recorded in the JSON and batch metadata artifacts.",
    ])
    return "\n".join(lines) + "\n"


def analyze(args):
    input_path = Path(args.input).resolve()
    batch_metadata_path = Path(args.batch_metadata).resolve()
    dataset_metadata_path = Path(args.dataset_metadata).resolve()
    photos = Path(args.photos).resolve()
    model = Path(args.model).resolve()
    mapping_page = Path(args.mapping_page).resolve()
    candidate_lock_path = Path(args.candidate_lock).resolve()
    evaluation_lock_path = Path(args.evaluation_lock).resolve()
    rows = read_csv(input_path)
    batch_metadata = read_json(batch_metadata_path)
    dataset = read_json(dataset_metadata_path)
    candidate_lock = read_json(candidate_lock_path)
    evaluation_lock = read_json(evaluation_lock_path)
    if batch_metadata.get("output_csv_sha256") != file_sha256(input_path):
        raise ValueError("batch metadata does not bind to production CSV")
    if batch_metadata.get("dataset_metadata_sha256") != file_sha256(dataset_metadata_path):
        raise ValueError("batch metadata does not bind to transform dataset metadata")
    if batch_metadata.get("manifest_sha256") != dataset.get("manifest_sha256"):
        raise ValueError("batch and transform dataset manifest hashes disagree")
    if candidate_lock.get("parent_evaluation_lock_sha256") != file_sha256(evaluation_lock_path):
        raise ValueError("candidate lock does not bind to evaluation lock")
    model_hash = file_sha256(model)
    if candidate_lock.get("candidate", {}).get("model_sha256") != model_hash:
        raise ValueError("candidate lock does not bind to model")
    if evaluation_lock.get("baseline", {}).get("model_sha256") != model_hash:
        raise ValueError("evaluation lock does not bind to model")
    reference = load_reference(mapping_page)
    session = ort.InferenceSession(str(model), providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name
    row_results = []
    candidate_inputs = []
    for row in rows:
        image_path = photos / row["filename"]
        if file_sha256(image_path) != row["image_sha256"]:
            raise ValueError(f"transform image hash mismatch: {row['filename']}")
        tensor, diagnostic = preprocess(image_path)
        candidate_inputs.append((row, tensor, diagnostic))
    for row, tensor, diagnostic in candidate_inputs:
        raw = float(session.run(None, {input_name: tensor[None, ...].astype(np.float32)})[0].reshape(-1)[0])
        candidate_continuous = score_from_raw(reference, raw)
        row_results.append({
            **row,
            "current_continuous": current_continuous(row),
            "current_public": current_public(row),
            "candidate_raw": raw,
            "candidate_continuous": candidate_continuous,
            "candidate_public": public_half_point(candidate_continuous),
            "candidate_letterbox_fraction": diagnostic["letterbox_fraction"],
            "current_score_form": score_form(row),
            "current_interval_width": interval_width(row),
            "current_route": row.get("routing") or "refused",
            "current_sex": row.get("sex") or "unknown",
            "current_framing": row.get("framing") or "unknown",
            "current_cues": row.get("geom_cues") or "none",
        })
    originals = {row["source_image_id"]: row for row in row_results if row["transform"] == "original"}
    if len(originals) * len(TRANSFORMS) != len(row_results):
        raise ValueError("each selected source must contain every registered transform exactly once")
    route_transitions = Counter()
    refusal_reasons = Counter()
    for row in row_results:
        baseline = originals[row["source_image_id"]]
        row["current_delta"] = (row["current_continuous"] - baseline["current_continuous"]
                                if row["current_continuous"] is not None and baseline["current_continuous"] is not None else None)
        row["candidate_delta"] = row["candidate_continuous"] - baseline["candidate_continuous"]
        current_padding = number(row.get("crop_padding_fraction"))
        baseline_padding = number(baseline.get("crop_padding_fraction"))
        row["crop_padding_delta"] = current_padding - baseline_padding if current_padding is not None and baseline_padding is not None else None
        row["current_public_changed"] = (row["current_public"] != baseline["current_public"]
                                         if row["current_public"] is not None and baseline["current_public"] is not None else None)
        row["candidate_public_changed"] = row["candidate_public"] != baseline["candidate_public"]
        row["route_transition"] = row["current_route"] != baseline["current_route"]
        if row["transform"] != "original" and row["route_transition"]:
            route_transitions[f"{baseline['current_route']} -> {row['current_route']}"] += 1
        if row["transform"] != "original" and row["current_continuous"] is None:
            refusal_reasons[row.get("refusal") or row.get("cause") or "unspecified"] += 1
    by_transform = {}
    for name, _, _ in TRANSFORMS:
        group = [row for row in row_results if row["transform"] == name]
        indexed = {row["source_image_id"]: row for row in group}
        common_indexed = {row["source_image_id"]: row for row in group if row["current_delta"] is not None}
        by_transform[name] = {
            "sources": len(group),
            "current_scored": sum(row["current_continuous"] is not None for row in group),
            "current_refused": sum(row["current_continuous"] is None for row in group),
            "route_transitions": sum(bool(row["route_transition"]) for row in group),
            "current_delta": summarize_delta([row["current_delta"] for row in group]),
            "candidate_delta": summarize_delta([row["candidate_delta"] for row in group]),
            "candidate_delta_common_current_pairs": summarize_delta([row["candidate_delta"] for row in group if row["current_delta"] is not None]),
            "current_public_changed": sum(row["current_public_changed"] is True for row in group),
            "candidate_public_changed": sum(row["candidate_public_changed"] is True for row in group),
            "current_ordering": ordering(originals, indexed, "current_continuous"),
            "current_public_ordering": ordering(originals, indexed, "current_public"),
            "candidate_ordering": ordering(originals, indexed, "candidate_continuous"),
            "candidate_ordering_common_current_pairs": ordering(originals, common_indexed, "candidate_continuous"),
            "candidate_public_ordering": ordering(originals, indexed, "candidate_public"),
            "crop_padding": crop_padding_diagnostic(group, score_key="current_continuous", delta_key="current_delta"),
        }
    material_regressions = []
    for name, item in by_transform.items():
        if name == "original":
            continue
        issues = []
        current_mae = item["current_delta"]["mean_absolute"]
        candidate_mae = item["candidate_delta_common_current_pairs"]["mean_absolute"]
        current_rank = item["current_ordering"]["spearman_vs_original"]
        candidate_rank = item["candidate_ordering_common_current_pairs"]["spearman_vs_original"]
        if current_mae is not None and candidate_mae is not None and candidate_mae - current_mae > .10:
            issues.append({"metric": "mean_absolute_delta", "candidate_minus_current": candidate_mae - current_mae})
        if current_rank is not None and candidate_rank is not None and candidate_rank - current_rank < -.10:
            issues.append({"metric": "rank_retention", "candidate_minus_current": candidate_rank - current_rank})
        if issues:
            material_regressions.append({"transform": name, "issues": issues})
    stability_passed = not material_regressions
    candidate_decision = ("Not approved for production: the registered synthetic stability screen passed, but the broader body-specific scope requirement did not."
                          if stability_passed else "Rejected for production: the narrow accuracy screen passed, but the registered synthetic stability screen showed material regressions and broader body-specific scope is absent.")
    non_control = [row for row in row_results if row["transform"] != "original"]
    crop_diagnostic = crop_padding_diagnostic(row_results, score_key="current_continuous", delta_key="current_delta")
    crop_diagnostic["paired_score_delta_sensitivity"] = crop_padding_diagnostic(non_control, score_key="current_continuous", delta_key="current_delta")["paired_score_delta_sensitivity"]
    paired_padding_rows = [
        row for row in non_control
        if number(row.get("crop_padding_delta")) is not None and number(row.get("current_delta")) is not None
    ]
    padding_deltas = [number(row["crop_padding_delta"]) for row in paired_padding_rows]
    score_deltas = [number(row["current_delta"]) for row in paired_padding_rows]
    crop_diagnostic["paired_padding_change_sensitivity"] = {
        "n": len(paired_padding_rows),
        "padding_fraction_delta": numeric_distribution(padding_deltas),
        "padding_delta_vs_score_delta_spearman": spearman(padding_deltas, score_deltas) if len(paired_padding_rows) >= 3 else None,
        "padding_delta_vs_score_delta_pearson": pearson(padding_deltas, score_deltas) if len(paired_padding_rows) >= 3 else None,
        "interpretation": "Within-source synthetic transforms quantify association between a changed production padding fraction and score change; transforms also change pixels/framing, so this is sensitivity evidence, not a randomized causal estimate.",
    }
    overview = {
        "rows": len(row_results),
        "sources": len(originals),
        "transforms": len(TRANSFORMS),
        "current_scored": sum(row["current_continuous"] is not None for row in row_results),
        "current_refused": sum(row["current_continuous"] is None for row in row_results),
        "current_refusal_rate": sum(row["current_continuous"] is None for row in row_results) / len(row_results),
        "current_interval_midpoint_rows": sum(row["current_score_form"] == "interval_midpoint" for row in row_results),
        "current_delta": summarize_delta([row["current_delta"] for row in non_control]),
        "candidate_delta": summarize_delta([row["candidate_delta"] for row in non_control]),
        "candidate_delta_common_current_pairs": summarize_delta([row["candidate_delta"] for row in non_control if row["current_delta"] is not None]),
        "current_public_changed_rate": (sum(row["current_public_changed"] is True for row in non_control)
                                        / sum(row["current_public_changed"] is not None for row in non_control)),
        "candidate_public_changed_rate": sum(row["candidate_public_changed"] is True for row in non_control) / len(non_control),
    }
    output_rows = []
    for row in row_results:
        output_rows.append({key: row.get(key) for key in (
            "image_id", "source_image_id", "transform", "transform_family", "label_quartile",
            "baseline_outcome", "outcome", "refusal", "cause", "current_route", "current_sex",
            "crop_side_px", "crop_padding_fraction", "crop_outside", "crop_padding_delta",
            "current_framing", "current_cues", "current_score_form", "current_interval_width", "current_continuous", "current_public", "current_delta",
            "current_public_changed", "route_transition", "candidate_raw", "candidate_continuous",
            "candidate_public", "candidate_delta", "candidate_public_changed", "candidate_letterbox_fraction",
        )})
    rows_output = Path(args.rows_output)
    write_csv(rows_output, output_rows, list(output_rows[0]))
    report = {
        "schema_version": "body-transform-stability-evaluation.v1",
        "interpretation": {
            "instrument": "Current production routing/pose crop versus the locked training-style full-image black-letterbox candidate with identical ONNX weights.",
            "discrimination": "Preprocessing can change ordering; these synthetic same-stimulus transforms measure consistency, not independent attractiveness discrimination.",
            "calibration": "Public half-point display metrics are separate. A monotone remap cannot improve rank/AUC/pairwise ordering and adds no attractiveness intelligence.",
            "candidate_decision": candidate_decision,
        },
        "overview": overview,
        "crop_padding_diagnostic": crop_diagnostic,
        "by_transform": by_transform,
        "route_transitions": dict(sorted(route_transitions.items())),
        "candidate_stability_screen": {
            "passed": stability_passed,
            "descriptive_material_thresholds": {"mae_regression": 0.10, "rank_retention_regression": 0.10},
            "material_regressions": material_regressions,
            "comparison_basis": "Candidate and production metrics use the identical sources with finite production originals and transforms.",
        },
        "refusal_reasons": dict(sorted(refusal_reasons.items())),
        "slices": {
            field: grouped(non_control, field) for field in (
                "transform_family", "label_quartile", "baseline_outcome", "current_route",
                "current_sex", "current_framing", "current_cues",
            )
        },
        "provenance": {
            "input_csv": {"path": str(input_path), "sha256": file_sha256(input_path)},
            "batch_metadata": {"path": str(batch_metadata_path), "sha256": file_sha256(batch_metadata_path)},
            "dataset_metadata": {"path": str(dataset_metadata_path), "sha256": file_sha256(dataset_metadata_path)},
            "manifest_sha256": dataset["manifest_sha256"],
            "model": {"path": str(model), "sha256": model_hash},
            "mapping_page": {"path": str(mapping_page), "sha256": file_sha256(mapping_page)},
            "candidate_lock": {"path": str(candidate_lock_path), "sha256": file_sha256(candidate_lock_path)},
            "evaluation_lock": {"path": str(evaluation_lock_path), "sha256": file_sha256(evaluation_lock_path)},
            "tool_sha256": file_sha256(Path(__file__).resolve()),
            "rows_output": {"path": str(rows_output), "sha256": file_sha256(rows_output)},
            "command": [str(value) for value in __import__("sys").argv],
        },
        "limitations": dataset["scope"]["limitations"],
    }
    output_json = Path(args.output_json)
    output_md = Path(args.output_md)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    output_md.write_text(markdown(report), encoding="utf-8", newline="\n")
    print(json.dumps(overview, indent=2))


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    prepare_parser = subparsers.add_parser("prepare")
    prepare_parser.add_argument("--source-manifest", required=True)
    prepare_parser.add_argument("--source-batch", required=True)
    prepare_parser.add_argument("--source-batch-metadata", required=True)
    prepare_parser.add_argument("--source-metadata", required=True)
    prepare_parser.add_argument("--photos", required=True)
    prepare_parser.add_argument("--cache-dir", required=True)
    prepare_parser.add_argument("--manifest-out", required=True)
    prepare_parser.add_argument("--metadata-out", required=True)
    analyze_parser = subparsers.add_parser("analyze")
    analyze_parser.add_argument("--input", required=True)
    analyze_parser.add_argument("--batch-metadata", required=True)
    analyze_parser.add_argument("--dataset-metadata", required=True)
    analyze_parser.add_argument("--photos", required=True)
    analyze_parser.add_argument("--model", default="models/body-beauty.onnx")
    analyze_parser.add_argument("--mapping-page", default="body.html")
    analyze_parser.add_argument("--candidate-lock", default="data/body-preprocessing-candidate-lock-v1.json")
    analyze_parser.add_argument("--evaluation-lock", default="data/body-evaluation-lock-v1.json")
    analyze_parser.add_argument("--output-json", required=True)
    analyze_parser.add_argument("--rows-output", required=True)
    analyze_parser.add_argument("--output-md", required=True)
    args = parser.parse_args()
    if args.command == "prepare":
        prepare(args)
    else:
        analyze(args)


if __name__ == "__main__":
    main()
